<a href="https://colab.research.google.com/github/manishsaini15/Encoder_Decoder_Concepts/blob/tokenisation-and-Padding-and-Input-and-output-related-concepts/Simple_Padding_RNN_Encoder_Decoder_concept.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import re
import numpy as np
from collections import Counter

In [2]:
# -----------------------------
# 1. Dataset
# -----------------------------
sentence_pairs = [
    ("i am happy", "मैं खुश हूँ"),
    ("i am sad", "मैं दुखी हूँ"),
    ("i am a student", "मैं एक छात्र हूँ"),
    ("you are my friend", "आप मेरे दोस्त हैं"),
    ("he is a teacher", "वह एक शिक्षक है"),
    ("she is reading a book", "वह एक किताब पढ़ रही है"),
    ("i like tea", "मुझे चाय पसंद है"),
    ("i like coffee", "मुझे कॉफी पसंद है"),
    ("we are going home", "हम घर जा रहे हैं"),
    ("they are playing", "वे खेल रहे हैं"),
    ("what is your name", "आपका नाम क्या है"),
    ("my name is rahul", "मेरा नाम राहुल है"),
    ("how are you", "आप कैसे हैं"),
    ("i am fine", "मैं ठीक हूँ"),
    ("good morning", "सुप्रभात"),
    ("good night", "शुभ रात्रि"),
    ("thank you", "धन्यवाद"),
    ("see you tomorrow", "कल मिलते हैं"),
    ("where are you going", "आप कहाँ जा रहे हैं"),
    ("i live in bangalore", "मैं बैंगलोर में रहता हूँ"),
    ("this is my book", "यह मेरी किताब है"),
    ("that is a car", "वह एक कार है"),
    ("we love india", "हम भारत से प्यार करते हैं"),
    ("open the door", "दरवाजा खोलो"),
    ("close the window", "खिड़की बंद करो"),
    ("the child is sleeping", "बच्चा सो रहा है"),
    ("the sun is bright", "सूरज तेज है"),
    ("today is a holiday", "आज छुट्टी है"),
    ("i am learning ai", "मैं एआई सीख रहा हूँ"),
    ("this is a simple example", "यह एक सरल उदाहरण है")
]

In [3]:
# -----------------------------
# 2. Text cleaning functions
# -----------------------------
def clean_english_text(text):
    text = text.lower().strip()
    text = re.sub(r"[^a-zA-Z0-9\s]", "", text)
    text = re.sub(r"\s+", " ", text)
    return text

def clean_hindi_text(text):
    text = text.strip()
    text = re.sub(r"\s+", " ", text)
    return text


In [4]:
# -----------------------------
# 3. Clean dataset
# -----------------------------
cleaned_pairs = []
for eng, hin in sentence_pairs:
    eng_clean = clean_english_text(eng)
    hin_clean = clean_hindi_text(hin)
    cleaned_pairs.append((eng_clean, hin_clean))


In [5]:
print(cleaned_pairs)

[('i am happy', 'मैं खुश हूँ'), ('i am sad', 'मैं दुखी हूँ'), ('i am a student', 'मैं एक छात्र हूँ'), ('you are my friend', 'आप मेरे दोस्त हैं'), ('he is a teacher', 'वह एक शिक्षक है'), ('she is reading a book', 'वह एक किताब पढ़ रही है'), ('i like tea', 'मुझे चाय पसंद है'), ('i like coffee', 'मुझे कॉफी पसंद है'), ('we are going home', 'हम घर जा रहे हैं'), ('they are playing', 'वे खेल रहे हैं'), ('what is your name', 'आपका नाम क्या है'), ('my name is rahul', 'मेरा नाम राहुल है'), ('how are you', 'आप कैसे हैं'), ('i am fine', 'मैं ठीक हूँ'), ('good morning', 'सुप्रभात'), ('good night', 'शुभ रात्रि'), ('thank you', 'धन्यवाद'), ('see you tomorrow', 'कल मिलते हैं'), ('where are you going', 'आप कहाँ जा रहे हैं'), ('i live in bangalore', 'मैं बैंगलोर में रहता हूँ'), ('this is my book', 'यह मेरी किताब है'), ('that is a car', 'वह एक कार है'), ('we love india', 'हम भारत से प्यार करते हैं'), ('open the door', 'दरवाजा खोलो'), ('close the window', 'खिड़की बंद करो'), ('the child is sleeping', 'बच्चा

In [6]:
# -----------------------------
# 4. Add special tokens to target sentences
# -----------------------------
START_TOKEN = "<start>"
END_TOKEN = "<end>"
PAD_TOKEN = "<pad>"
UNK_TOKEN = "<unk>"

processed_pairs = []
for eng, hin in cleaned_pairs:
    hin_with_tokens = f"{START_TOKEN} {hin} {END_TOKEN}"
    processed_pairs.append((eng, hin_with_tokens))


In [8]:
for i in range(5):
  print(processed_pairs[i][1])

<start> मैं खुश हूँ <end>
<start> मैं दुखी हूँ <end>
<start> मैं एक छात्र हूँ <end>
<start> आप मेरे दोस्त हैं <end>
<start> वह एक शिक्षक है <end>


In [9]:
# -----------------------------
# 5. Tokenization (simple split-based)
# -----------------------------
def tokenize(text):
    return text.split()

source_sentences = [eng for eng, hin in processed_pairs]
target_sentences = [hin for eng, hin in processed_pairs]

source_tokenized = [tokenize(sent) for sent in source_sentences]
target_tokenized = [tokenize(sent) for sent in target_sentences]


In [13]:
for i in  target_tokenized:
  print(i)

['<start>', 'मैं', 'खुश', 'हूँ', '<end>']
['<start>', 'मैं', 'दुखी', 'हूँ', '<end>']
['<start>', 'मैं', 'एक', 'छात्र', 'हूँ', '<end>']
['<start>', 'आप', 'मेरे', 'दोस्त', 'हैं', '<end>']
['<start>', 'वह', 'एक', 'शिक्षक', 'है', '<end>']
['<start>', 'वह', 'एक', 'किताब', 'पढ़', 'रही', 'है', '<end>']
['<start>', 'मुझे', 'चाय', 'पसंद', 'है', '<end>']
['<start>', 'मुझे', 'कॉफी', 'पसंद', 'है', '<end>']
['<start>', 'हम', 'घर', 'जा', 'रहे', 'हैं', '<end>']
['<start>', 'वे', 'खेल', 'रहे', 'हैं', '<end>']
['<start>', 'आपका', 'नाम', 'क्या', 'है', '<end>']
['<start>', 'मेरा', 'नाम', 'राहुल', 'है', '<end>']
['<start>', 'आप', 'कैसे', 'हैं', '<end>']
['<start>', 'मैं', 'ठीक', 'हूँ', '<end>']
['<start>', 'सुप्रभात', '<end>']
['<start>', 'शुभ', 'रात्रि', '<end>']
['<start>', 'धन्यवाद', '<end>']
['<start>', 'कल', 'मिलते', 'हैं', '<end>']
['<start>', 'आप', 'कहाँ', 'जा', 'रहे', 'हैं', '<end>']
['<start>', 'मैं', 'बैंगलोर', 'में', 'रहता', 'हूँ', '<end>']
['<start>', 'यह', 'मेरी', 'किताब', 'है', '<end>']
['<s

In [15]:
# -----------------------------
# 6. Build vocabularies
# -----------------------------
def build_vocab(tokenized_sentences, add_special_tokens=True):
    counter = Counter()
    for sent in tokenized_sentences:
        counter.update(sent)

    print(counter)

    vocab = {}
    index = 0

    if add_special_tokens:
        vocab[PAD_TOKEN] = index
        index += 1
        vocab[UNK_TOKEN] = index
        index += 1

    for word, _ in counter.items():
        if word not in vocab:
            vocab[word] = index
            index += 1

    print(vocab)

    return vocab

source_vocab = build_vocab(source_tokenized, add_special_tokens=True)
target_vocab = build_vocab(target_tokenized, add_special_tokens=True)

# Reverse vocabularies for decoding
source_index_to_word = {idx: word for word, idx in source_vocab.items()}
target_index_to_word = {idx: word for word, idx in target_vocab.items()}


Counter({'is': 10, 'i': 8, 'a': 6, 'am': 5, 'you': 5, 'are': 5, 'the': 4, 'my': 3, 'book': 2, 'like': 2, 'we': 2, 'going': 2, 'name': 2, 'good': 2, 'this': 2, 'happy': 1, 'sad': 1, 'student': 1, 'friend': 1, 'he': 1, 'teacher': 1, 'she': 1, 'reading': 1, 'tea': 1, 'coffee': 1, 'home': 1, 'they': 1, 'playing': 1, 'what': 1, 'your': 1, 'rahul': 1, 'how': 1, 'fine': 1, 'morning': 1, 'night': 1, 'thank': 1, 'see': 1, 'tomorrow': 1, 'where': 1, 'live': 1, 'in': 1, 'bangalore': 1, 'that': 1, 'car': 1, 'love': 1, 'india': 1, 'open': 1, 'door': 1, 'close': 1, 'window': 1, 'child': 1, 'sleeping': 1, 'sun': 1, 'bright': 1, 'today': 1, 'holiday': 1, 'learning': 1, 'ai': 1, 'simple': 1, 'example': 1})
{'<pad>': 0, '<unk>': 1, 'i': 2, 'am': 3, 'happy': 4, 'sad': 5, 'a': 6, 'student': 7, 'you': 8, 'are': 9, 'my': 10, 'friend': 11, 'he': 12, 'is': 13, 'teacher': 14, 'she': 15, 'reading': 16, 'book': 17, 'like': 18, 'tea': 19, 'coffee': 20, 'we': 21, 'going': 22, 'home': 23, 'they': 24, 'playing': 25,

In [16]:
# -----------------------------
# 7. Convert tokenized sentences to integer sequences
# -----------------------------
def sentence_to_sequence(tokenized_sentence, vocab):
    return [vocab.get(word, vocab[UNK_TOKEN]) for word in tokenized_sentence]

source_sequences = [sentence_to_sequence(sent, source_vocab) for sent in source_tokenized]
target_sequences = [sentence_to_sequence(sent, target_vocab) for sent in target_tokenized]

In [17]:
# -----------------------------
# 8. Find maximum lengths
# -----------------------------
max_source_len = max(len(seq) for seq in source_sequences)
max_target_len = max(len(seq) for seq in target_sequences)


In [18]:
# -----------------------------
# 9. Pad sequences
# -----------------------------
def pad_sequence(sequence, max_len, pad_value=0):
    return sequence + [pad_value] * (max_len - len(sequence))

encoder_input_data = np.array([
    pad_sequence(seq, max_source_len, pad_value=source_vocab[PAD_TOKEN])
    for seq in source_sequences
])

target_padded = np.array([
    pad_sequence(seq, max_target_len, pad_value=target_vocab[PAD_TOKEN])
    for seq in target_sequences
])

In [20]:
print(encoder_input_data[0], target_padded[0])

[2 3 4 0 0] [2 3 4 5 6 0 0 0]


In [24]:
# -----------------------------
# 10. Prepare decoder input and decoder target
# -----------------------------
decoder_input_data = target_padded[:, :-1] # last column remove becaue it contains <end>
decoder_target_data = target_padded[:, 1:] # rmove first column because it contains <start>
print(decoder_target_data[0])


# Expand last dimension for sparse categorical crossentropy later
decoder_target_data = np.expand_dims(decoder_target_data, -1)
print(decoder_target_data[0])


[3 4 5 6 0 0 0]
[[3]
 [4]
 [5]
 [6]
 [0]
 [0]
 [0]]


In [25]:
# -----------------------------
# 11. Display summary
# -----------------------------
print("Total sentence pairs:", len(processed_pairs))
print("Source vocabulary size:", len(source_vocab))
print("Target vocabulary size:", len(target_vocab))
print("Max source sentence length:", max_source_len)
print("Max target sentence length:", max_target_len)

print("\nSample processed pair:")
print("English:", processed_pairs[0][0])
print("Hindi :", processed_pairs[0][1])

print("\nSample source tokenized:", source_tokenized[0])
print("Sample target tokenized:", target_tokenized[0])

print("\nSample source sequence:", source_sequences[0])
print("Sample target sequence:", target_sequences[0])

print("\nEncoder input shape:", encoder_input_data.shape)
print("Decoder input shape:", decoder_input_data.shape)
print("Decoder target shape:", decoder_target_data.shape)

Total sentence pairs: 30
Source vocabulary size: 62
Target vocabulary size: 70
Max source sentence length: 5
Max target sentence length: 8

Sample processed pair:
English: i am happy
Hindi : <start> मैं खुश हूँ <end>

Sample source tokenized: ['i', 'am', 'happy']
Sample target tokenized: ['<start>', 'मैं', 'खुश', 'हूँ', '<end>']

Sample source sequence: [2, 3, 4]
Sample target sequence: [2, 3, 4, 5, 6]

Encoder input shape: (30, 5)
Decoder input shape: (30, 7)
Decoder target shape: (30, 7, 1)


In [26]:
# -----------------------------
# 12. Show one example clearly
# -----------------------------
example_index = 0
print("\n--- Example walkthrough ---")
print("Original English sentence :", source_sentences[example_index])
print("Original Hindi sentence   :", target_sentences[example_index])
print("Encoder input IDs         :", encoder_input_data[example_index])
print("Decoder input IDs         :", decoder_input_data[example_index])
print("Decoder target IDs        :", decoder_target_data[example_index].flatten())

print("\nDecoder input words:")
print([target_index_to_word.get(idx, UNK_TOKEN) for idx in decoder_input_data[example_index]])

print("Decoder target words:")
print([target_index_to_word.get(idx, UNK_TOKEN) for idx in decoder_target_data[example_index].flatten()])



--- Example walkthrough ---
Original English sentence : i am happy
Original Hindi sentence   : <start> मैं खुश हूँ <end>
Encoder input IDs         : [2 3 4 0 0]
Decoder input IDs         : [2 3 4 5 6 0 0]
Decoder target IDs        : [3 4 5 6 0 0 0]

Decoder input words:
['<start>', 'मैं', 'खुश', 'हूँ', '<end>', '<pad>', '<pad>']
Decoder target words:
['मैं', 'खुश', 'हूँ', '<end>', '<pad>', '<pad>', '<pad>']


In [27]:
#-------------------------------------------------------

from tensorflow.keras.layers import Embedding
import tensorflow as tf

from tensorflow.keras.layers import Embedding
import tensorflow as tf

sample_vocab_size = len(source_vocab)
embedding_dim = 8

embedding_layer = Embedding(input_dim=sample_vocab_size, output_dim=embedding_dim)

sample_input = tf.constant([[2, 3, 4]])
sample_output = embedding_layer(sample_input)

print("Input shape :", sample_input.shape)
print("Output shape:", sample_output.shape)
print(sample_output.numpy())

Input shape : (1, 3)
Output shape: (1, 3, 8)
[[[-0.02724841 -0.01485416  0.04174824 -0.03061648  0.03409492
   -0.03426782 -0.00263908  0.03315035]
  [-0.03907856 -0.03804078  0.01960165  0.00014665  0.00402514
   -0.02830586 -0.005669   -0.04041634]
  [-0.0412342   0.0245469  -0.03661408  0.00713197 -0.01160868
    0.03080786  0.02184448  0.00526706]]]


In [28]:
#--------------------------------------
for i in range(5):
    print(processed_pairs[i])


#---------------------------------------

print(source_tokenized[0])
print(target_tokenized[0])

#------------------------------------


print("Source vocab sample:", list(source_vocab.items())[:10])
print("Target vocab sample:", list(target_vocab.items())[:10])



#----------------------------------------

print("English sentence :", source_sentences[0])
print("Sequence         :", source_sequences[0])

print("Hindi sentence   :", target_sentences[0])
print("Sequence         :", target_sequences[0])


('i am happy', '<start> मैं खुश हूँ <end>')
('i am sad', '<start> मैं दुखी हूँ <end>')
('i am a student', '<start> मैं एक छात्र हूँ <end>')
('you are my friend', '<start> आप मेरे दोस्त हैं <end>')
('he is a teacher', '<start> वह एक शिक्षक है <end>')
['i', 'am', 'happy']
['<start>', 'मैं', 'खुश', 'हूँ', '<end>']
Source vocab sample: [('<pad>', 0), ('<unk>', 1), ('i', 2), ('am', 3), ('happy', 4), ('sad', 5), ('a', 6), ('student', 7), ('you', 8), ('are', 9)]
Target vocab sample: [('<pad>', 0), ('<unk>', 1), ('<start>', 2), ('मैं', 3), ('खुश', 4), ('हूँ', 5), ('<end>', 6), ('दुखी', 7), ('एक', 8), ('छात्र', 9)]
English sentence : i am happy
Sequence         : [2, 3, 4]
Hindi sentence   : <start> मैं खुश हूँ <end>
Sequence         : [2, 3, 4, 5, 6]


In [29]:
#-----------------------------------------

print("Before padding:", source_sequences[0])
print("After padding :", encoder_input_data[0])


#------------------------------------------
print("Decoder input IDs :", decoder_input_data[0])
print("Decoder target IDs:", decoder_target_data[0].flatten())

print("Decoder input words :",
      [target_index_to_word[idx] for idx in decoder_input_data[0]])

print("Decoder target words:",
      [target_index_to_word[idx] for idx in decoder_target_data[0].flatten()])

Before padding: [2, 3, 4]
After padding : [2 3 4 0 0]
Decoder input IDs : [2 3 4 5 6 0 0]
Decoder target IDs: [3 4 5 6 0 0 0]
Decoder input words : ['<start>', 'मैं', 'खुश', 'हूँ', '<end>', '<pad>', '<pad>']
Decoder target words: ['मैं', 'खुश', 'हूँ', '<end>', '<pad>', '<pad>', '<pad>']
